name: Continous Integration
on: [pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
#      - name: Check format
#        run: sh scripts/format-csharp --check
      - name: Build
        run: sh dbuild.sh
