name: Continous Integration
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, arch: x64, name: ubuntu-x64 }
          - { os: macos-latest, arch: x64, name: macos-x64 }
          - { os: windows-latest, arch: x64, name: windows-x64 }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Check format
        run: dotnet format Source/gtk-sharp.sln --verify-no-changes
      - name: Install Deps
        run: pip3 install meson ninja
      - name: Install Windows Deps
        if: matrix.config.os == 'windows-latest'
        run: choco install winflexbison3 -y
      - name: Configure
        run: meson builddir --buildtype=release
      - name: Build
        run: meson compile -C builddir
      - name: Install
        run: meson install -C builddir
      - name: Build dotnet
        run: dotnet build Source/gtk-sharp.sln /p:Platform="Any CPU"
      - name: Test
        run: dotnet test Source/gtk-sharp.sln /p:Platform="Any CPU"
